function addRoutePopup(callbackFunc){  
	s = '';  
	s += '<style>';  
	s += '  #formDiv {';  
	s += '   position: absolute;';  
	s += '   top: 200px;';  
	s += '   left: 500px;';  
	s += '   background-color: #DCE3EB;';  
	s += '   color: #33532F;';  
	s += '   border: 1px solid #33532F;';  
	s += '   padding: 12px 6px 0px 6px;';  
	s += '   font-family: Tahoma, Helvetica, sans-serif;';  
	s += '   font-size: 9pt; ';  
	s += '   text-align: center; ';  
	s += '  }';  
	s += '</style>';  
	s += '';  
	s += '<div id="formDiv">';  
	s += '  <strong>New Route</strong><br /><br />';  
	s += '  <form name="newRouteForm" id="newRouteForm" method="post">';  
	s += '  Route Name: <input id="routeName" name="routeName" type="text" class="SiteTextBox" /><br /><br />';  	
	s += '  <input type="submit" name="btnSave" id="btnSave" value="Create" class="SiteSubmitbox">&nbsp;&nbsp;<input type="button" name="btnCancel" id="btnCancel" value="Cancel" class="SiteSubmitbox">';  
	s += '  </form>';  
	s += '</div>';  
	s += '';  
	s += '<script type="text/javascript">';  
	s += '  formInfo = "";';  
	s += '  $("#btnCancel").click(function(){';  
	s += '    returnResponse("Cancelled");';  
	s += '  });';  
	s += '  $("#newRouteForm").submit(function(){';  
	s += '    formInfo = new Object;';  
	s += '    formInfo.routeName = $("#routeName").val();';  
	s += '    returnResponse(formInfo);';  
	s += '  });';  
	s += '  function returnResponse(fI){';  
	s += '    $("#formDiv").remove();';  
	s += '    ' + callbackFunc + '(fI);';  
	s += '  }';  
	s += '</script>';  
	$("body").append(s);
	$('#routeName').focus();
}
